### PR TITLE
Random stubs for HMD & login functions

### PR DESCRIPTION
**Pull request by whatdahopper**
Gets Beat Saber (1.00) booting to the Unity splashscreen and then dies due to unimplemented/stub HMD functions.

image

Also stubs `sceLoginDialogInitialize`, which might help with other games. Not ready for merging yet, as I do want to improve these stubs.

### CODE REVIEW

**Comment by ghost** [comment]
The first VR game is booting? I searched up this game and it said it uses VR

**Comment by ghost** [comment]
Also, this PR can allow No Man's SKy to go further as it uses one of the sceHmd functions implemented here.

**Comment by ghost** [comment]
Built this build myself, tried No Man's Sky (original version) and got this:
```
[TTY]:Reducing GPU memory pool from 1445 mb to 0 mb
srchd:0000000000..0180000000 len:0000000000
align:0000010000 mType:WC_GARLIC
[WARN]:sceKernelAllocateDirectMemory:22
[TTY]:sce::Gnm::Initialize Error: Shared Gpu Memory Allocation Failed (-2147352554)
[TTY]:Shared System size    : 0x0038C00000
[TTY]:Shared System CPU Addr: 0x08023151F8
[TTY]:Shared Video size     : 0x0000000000
[TTY]:Shared Video CPU Addr : 0x0802315200
Message: Access violation (216)
  $0000000009F74A32 offset $00044A32 libc.prx:memset+$00000062
  $0000000800FC0B9C offset $00FC0B9C eboot.bin:dtInit+$00FC0B7C
  $0000000800EBB93B offset $00EBB93B eboot.bin:dtInit+$00EBB91B
  $0000000800EBB45B offset $00EBB45B eboot.bin:dtInit+$00EBB43B
  $00000008000341AE offset $000341AE eboot.bin:dtInit+$0003418E
  $0000000800033ECF offset $00033ECF eboot.bin:dtInit+$00033EAF
  $0000000800033E99 offset $00033E99 eboot.bin:dtInit+$00033E79
  $0000000801020C1F offset $01020C1F eboot.bin:Entry+$0000003F
  $0000000000000001 fpPS4.exe
```

**Comment by and468860** [comment]
missing [main:1524] nop nid:libSceHmdSetupDialog:341D58DA40368C26:sceHmdSetupDialogInitialize

**Pull request merged**
