### PR TITLE
Updated the fpPS4 logo

### PR DESCRIPTION
**Pull request by SoffiMeower**
Decided to update the fpPS4 logo based on feedback in the discord server!
Old:
logo (1)
New:
logo
Larger resolution, smoother text, metalic coloring for the PS4 text, gradient in the background. It also has a small outline around the text.

### CODE REVIEW

**Comment by ghost** [comment]
This looks magnitudes better than the original MS Paint one!

**Comment by red-prig** [comment]
Why did you remove *.ico ? It is necessary to leave the old icon, or offer a new one.

**Comment by SoffiMeower** [comment]
> Why did you remove *.ico ? It is necessary to leave the old icon, or offer a new one.

I didn't remove them, it's just that the new ICOs have a smaller file size, so it shows as a negative value.

**Comment by SoffiMeower** [comment]
Tap "View Raw", it'll show the new files @red-prig

**Comment by red-prig** [comment]
I checked, somehow the ICO file is incorrect, it only contains the size 256x256, and should contain all sizes: 16x16, 24x24, 32x32, 48x48, 64x64, 128x128, 256x256. Normal resizing will look terrible, because it needs to be adapted to each specific size.

**Comment by SoffiMeower** [comment]
> I checked, somehow the ICO file is incorrect, it only contains the size 256x256, and should contain all sizes: 16x16, 24x24, 32x32, 48x48, 64x64, 128x128, 256x256. Normal resizing will look terrible, because it needs to be adapted to each specific size.

Ah, I'll fix that. Seems Krita didn't size scale. Any changes you want for smaller sizes?

**Comment by SoffiMeower** [comment]
Okay, so with 24x24 and 16x16, the text is too small to be read, I'm wondering if for those I should just have the text be an enlarged FP with the circle.

**Comment by red-prig** [comment]
the main thing is that even a smaller size is clearly recognizable

**Comment by SoffiMeower** [comment]
Should be fixed! @red-prig

**Pull request merged**
